name: Nuxt tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm ci
    - name: Build Nuxt
      run: npm run build
    - name: Run tests
      run: npm run test
